[build]
  builder = "nixpacks"
  buildCommand = "npm install --omit=dev"

[deploy]
  startCommand = "npm run init-db && npm start"
  healthcheckPath = "/api/health"

[env]
  NODE_ENV = "production"
  ALLOWED_ORIGINS = "https://shinpark43.github.io"
  DATABASE_PATH = "/app/data/facilities.db"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable" 