services:
  - type: web
    name: asu-facilities-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run init-db
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://shinpark43.github.io
      - key: DATABASE_PATH
        value: /tmp/facilities.db 